# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to clique
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:21.7.1
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:21.7.2
# * QUORUM_GETH_ARGS: extra geth arguments to be included when running geth
# To use Constellation, set QUORUM_TX_MANAGER_DOCKER_IMAGE to Constellation docker image,
# e.g.: QUORUM_TX_MANAGER_DOCKER_IMAGE=quorumengineering/constellation:0.3.2 docker-compose up -d
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
version: "3.6"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:21.7.1}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-clique}
  entrypoint:
    - /bin/sh
    - -c
    - |
      UDS_WAIT=10
      if [ "$${PRIVATE_CONFIG}" != "ignore" ]; then
      for i in $$(seq 1 100)
      do
        set -e
        if [ -S $${PRIVATE_CONFIG} ] && \
          [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- --proxy off 172.16.239.10$${NODE_ID}:9000/upcheck)" ];
        then break
        else
          echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
          sleep $${UDS_WAIT}
        fi
      done
      fi
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /networkdata/keys/validator$${NODE_ID}/nodekey $${DDIR}/geth/nodekey
      cp /networkdata/keys/validator$${NODE_ID}/accountKeystore $${DDIR}/keystore/
      cp /networkdata/disallowed-nodes.json $${DDIR}/
      cat /networkdata/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/networkdata/istanbul-genesis.json"
      CONSENSUS_RPC_API="istanbul"
      if [ "${QUORUM_CONSENSUS:-clique}" == "clique" ]; then
        GENESIS_FILE="/networkdata/clique-genesis.json"
        CONSENSUS_RPC_API="quorumPermission,quorumExtension,clique"
      elif [ "${QUORUM_CONSENSUS:-clique}" == "raft" ]; then
        GENESIS_FILE="/networkdata/genesis.json"
        CONSENSUS_RPC_API="raft"
      elif [ "${QUORUM_CONSENSUS:-clique}" == "qbft" ]; then
        GENESIS_FILE="/networkdata/qbft-genesis.json"
      fi
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      GETH_ARGS_clique="--syncmode full --mine --miner.threads 1"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --miner.threads 1 --syncmode full"
      GETH_ARGS_qbft="--emitcheckpoints --istanbul.blockperiod 1 --mine --miner.threads 1 --syncmode full"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-clique} \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$${CONSENSUS_RPC_API} \
        --ws.addr 0.0.0.0 \
        --ws.port 8546 \
        --ws.api admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$${CONSENSUS_RPC_API} \
        --ws.origins * \
        --port 21000 \
        --unlock 0 \
        --allow-insecure-unlock \
        --nousb \
        --password /networkdata/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-clique}}
x-tx-manager-def:
  &tx-manager-def
  image: "${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:21.7.2}"
  expose:
    - "9000"
    - "9080"
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /qdata/tm/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      if [ "$${PRIVATE_CONFIG}" == "ignore" ]; then
        /bin/true
        exit 0
      fi
      DDIR=/qdata/tm
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:21.7}"
      TX_MANAGER=$$(echo $${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$$/\1/g')
      echo "TxManager: $${TX_MANAGER}"
      case $${TX_MANAGER}
      in
        tessera)
          cp /networkdata/keys/validator$${NODE_ID}/tessera.pub $${DDIR}/tm.pub
          cp /networkdata/keys/validator$${NODE_ID}/tessera.key $${DDIR}/tm.key
          if [ -f "/tessera/tessera-app.jar" ]; then
              TESSERA_VERSION=$$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
          else
              TESSERA_VERSION=$$(/tessera/bin/tessera version)
          fi
          echo "Tessera version: $${TESSERA_VERSION}"
          # sorting versions to target correct configuration
          V08=$$(echo -e "0.8\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
          V09AndAbove=$$(echo -e "0.9\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
          TESSERA_CONFIG_TYPE="-09"
          case "$${TESSERA_VERSION}" in
              "$${V09AndAbove}")
                  TESSERA_CONFIG_TYPE="-09"
                  ;;
          esac

          echo Config type $${TESSERA_CONFIG_TYPE}

          #generating the two config flavors
          cat <<EOF > $${DDIR}/tessera-config-09.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9080",
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverAddress": "unix:$${DDIR}/tm.ipc",
              "communicationType" : "REST"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9000",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://txmanager1:9000"
               },
               {
                   "url": "http://txmanager2:9000"
               },
               {
                   "url": "http://txmanager3:9000"
               },
               {
                   "url": "http://txmanager4:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat $${DDIR}/tm.key),
                  "publicKey": "$$(cat $${DDIR}/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF
          cat $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          if [ -f "/tessera/tessera-app.jar" ]; then
              java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          else
              export JAVA_OPTS="-Xms128M -Xmx128M"
              /tessera/bin/tessera -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          fi
          ;;
        constellation)
          echo "socket=\"$${DDIR}/tm.ipc\"\npublickeys=[\"/networkdata/keys/validator$${NODE_ID}/tessera.pub\"]\n" > $${DDIR}/tm.conf
          constellation-node \
            --url=http://$$(hostname -i):9000/ \
            --port=9000 \
            --socket=$${DDIR}/tm.ipc \
            --othernodes=http://172.16.239.101:9000/,http://172.16.239.102:9000/,http://172.16.239.103:9000/,http://172.16.239.104:9000/ \
            --publickeys=/networkdata/keys/validator$${NODE_ID}/tessera.pub \
            --privatekeys=/networkdata/keys/validator$${NODE_ID}/tessera.key \
            --storage=$${DDIR} \
            --verbosity=4
          ;;
        *)
          echo "Invalid Transaction Manager"
          exit 1
          ;;
      esac
x-cakeshop-def:
  &cakeshop-def
  image: "${CAKESHOP_DOCKER_IMAGE:-quorumengineering/cakeshop:0.12.1}"
  expose:
    - "8999"
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/cakeshop/local
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      cp /networkdata/cakeshop/application.properties.template $${DDIR}/application.properties
      cp /networkdata/cakeshop/7nodes_docker.json $${DDIR}/7nodes.json
      java -Xms128M -Xmx128M -Dspring.config.additional-location=file:/qdata/cakeshop/local/ -Dcakeshop.config.dir=/qdata/cakeshop -jar /cakeshop/cakeshop.war
      ;;
x-blockscout-ref:
  &blockscout-def
  image: consensys/blockscout:v4.0.0-beta
  container_name: blockscout
  restart: "no"
  environment:
    - PORT=4000
    - DATABASE_URL=ecto://postgres:postgres@blockscoutpostgres/postgres?ssl=false
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - NETWORK=fptlab
    - SUBNETWORK=Quorum
    - CHAIN_ID=10
    - COIN=ETH
    - ETHEREUM_JSONRPC_VARIANT=geth
    - ETHEREUM_JSONRPC_TRANSPORT=http
    - ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:22000
    - ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:22000
    - ETHEREUM_JSONRPC_WS_URL=ws://http://127.0.0.1:22010
  entrypoint:
    - /bin/sh
    - -c
    - |
      cd /opt/app/;
      echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
  depends_on:
    - blockscoutpostgres
  links:
    - blockscoutpostgres
  ports:
    - 26000:4000

x-blockscoutpostgres-ref:
  &blockscoutpostgres-def
  image: postgres:13.4-alpine
  restart: "on-failure"
  container_name: blockscoutpostgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
    - blockscoutpostgres:/var/lib/postgresql/data
  ports:
    - 5432
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 5s
    timeout: 10s
    retries: 5
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22000:8545"
      - "22010:8546"
    volumes:
      - vol1:/qdata
      - ./data:/networkdata:ro
    depends_on:
      - txmanager1
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=1
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.11
  txmanager1:
    << : *tx-manager-def
    hostname: txmanager1
    ports:
      - "9081:9080"
    volumes:
      - vol1:/qdata
      - ./data:/networkdata:ro
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.101
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=1
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22001:8545"
      - "22011:8546"
    volumes:
      - vol2:/qdata
      - ./data:/networkdata:ro
    depends_on:
      - txmanager2
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=2
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.12
  txmanager2:
    << : *tx-manager-def
    hostname: txmanager2
    ports:
      - "9082:9080"
    volumes:
      - vol2:/qdata
      - ./data:/networkdata:ro
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.102
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=2
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22002:8545"
      - "22012:8546"
    volumes:
      - vol3:/qdata
      - ./data:/networkdata:ro
    depends_on:
      - txmanager3
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=3
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.13
  txmanager3:
    << : *tx-manager-def
    hostname: txmanager3
    ports:
      - "9083:9080"
    volumes:
      - vol3:/qdata
      - ./data:/networkdata:ro
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.103
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=3
  node4:
    << : *quorum-def
    hostname: node4
    ports:
      - "22003:8545"
      - "22013:8546"
    volumes:
      - vol4:/qdata
      - ./data:/networkdata:ro
    depends_on:
      - txmanager4
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=4
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.14
  txmanager4:
    << : *tx-manager-def
    hostname: txmanager4
    ports:
      - "9084:9080"
    volumes:
      - vol4:/qdata
      - ./data:/networkdata:ro
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.104
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/qdata/tm/tm.ipc}
      - NODE_ID=4
  blockscout:
    << : *blockscout-def
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.51

  blockscoutpostgres:
    << : *blockscoutpostgres-def
    networks:
      quorum-dev-net:
        ipv4_address: 172.16.239.52
  # cakeshop:
  #   << : *cakeshop-def
  #   hostname: cakeshop
  #   ports:
  #     - "8999:8999"
  #     - "9999:8080"
  #   volumes:
  #     - cakeshopvol:/qdata
  #     - ./data:/networkdata:ro
  #   networks:
  #     quorum-dev-net:
  #       ipv4_address: 172.16.239.186
networks:
  quorum-dev-net:
    name: quorum-dev-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":
  "blockscoutpostgres":
  # "cakeshopvol":
