---
image:
  repository: consensys/quorum-k8s-hooks
  tag: latest
  pullPolicy: IfNotPresent

# local / azure
provider: local

# the number of Validators you want
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm: 
        consensus: clique # choose from: ibft | qbft | raft | clique
        blockperiodseconds: 5
        epochlength: 30000
        requesttimeoutseconds: 20
    nonce: '0x0'
    gasLimit: '0xE000000000'
    difficulty: '0x0'
    coinbase: '0x0000000000000000000000000000000000000000'
  blockchain:
    nodes:
      generate: true
      count: 7
